//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dblayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingTblTable
    {
        public int BookingTableID { get; set; }
        public int BookingUserID { get; set; }
        public string FullName { get; set; }
        public string EmailAddress { get; set; }
        public string MobileNo { get; set; }
        public System.DateTime BookingDate { get; set; }
        public System.DateTime ReservationDateTime { get; set; }
        public int NoOfPersons { get; set; }
        public int ProcessBy_UserID { get; set; }
        public int BookingStatusID { get; set; }
        public string Description { get; set; }
    
        public virtual BookingStatusTable BookingStatusTable { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
