//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dblayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockMenuItemTable
    {
        public int StockMenuItemID { get; set; }
        public int StockMenuCategoryID { get; set; }
        public int StockItemID { get; set; }
        public int VisibleStatusID { get; set; }
        public int CreatedBy_UserID { get; set; }
    
        public virtual StockItemTable StockItemTable { get; set; }
        public virtual VisibleStatusTable VisibleStatusTable { get; set; }
        public virtual StockItemCategoryTable StockItemCategoryTable { get; set; }
        public virtual StockMenuCategoryTable StockMenuCategoryTable { get; set; }
    }
}
