//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dblayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockItemReviewTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockItemReviewTable()
        {
            this.OrderTables = new HashSet<OrderTable>();
        }
    
        public int ItemReviewID { get; set; }
        public int StockItemID { get; set; }
        public int ReviewBy_UserID { get; set; }
        public System.DateTime ReviewDateTime { get; set; }
        public int Rating { get; set; }
        public string ReviewDetails { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderTable> OrderTables { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
