//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dblayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableReservationTable
    {
        public int TableReservationID { get; set; }
        public int Reservation_UserID { get; set; }
        public string FullName { get; set; }
        public string EmailAddress { get; set; }
        public string MobileNo { get; set; }
        public System.DateTime ReservationRequestDate { get; set; }
        public System.DateTime ReservationDateTime { get; set; }
        public int NoOfPersons { get; set; }
        public int ProcessBy_UserID { get; set; }
        public int ReservationStatusID { get; set; }
        public string Description { get; set; }
    
        public virtual ReservationStatusTable ReservationStatusTable { get; set; }
        public virtual UserTable UserTable { get; set; }
        public virtual UserTable UserTable1 { get; set; }
    }
}
